version: "1.0"
services:
  postgres:
    container_name: nettbutikk_compose
    image: postgres
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    networks:
      - default
    ports:
      - 5432:5432
  pgadmin:
    container_name: nettbutikk_viewer_compose
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - default
    ports:
      - 4000:80
networks:
  default:
    external: true
    name: postgres_network
